import type { RowDataPacket } from "mysql2";
import Link from "next/link";
import { ArrowLeft, PiggyBank } from "lucide-react";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { pool } from "@/lib/db";
import { createCapitalInjectionAction } from "./actions";
import styles from "./capital.module.css";
interface Row extends RowDataPacket{id:number;reference_number:string;injection_date:Date|string;amount:number;payment_method:string;remarks:string|null;created_by_name:string|null}
export default async function Page({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const user=await getCurrentUser();if(!user)redirect("/");if(!["ADMIN","OWNER"].includes(user.role))redirect("/dashboard");const p=await searchParams;const [rows]=await pool.query<Row[]>("SELECT ci.*,u.full_name created_by_name FROM capital_injections ci LEFT JOIN users u ON u.id=ci.created_by ORDER BY ci.injection_date DESC,ci.id DESC LIMIT 200");const money=(v:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(v||0));return <main className={styles.page}><div className={styles.topbar}><Link href="/dashboard"><ArrowLeft size={17}/>Dashboard</Link></div><section className={styles.hero}><div><span>Finance</span><h1>Capital Injection</h1><p>Add owner/business capital without changing the original opening balance.</p></div><PiggyBank size={46}/></section>{p.success?<div className={styles.success}>{p.success}</div>:null}{p.error?<div className={styles.error}>{p.error}</div>:null}<section className={styles.card}><form action={createCapitalInjectionAction} className={styles.form}><label>Amount<input type="number" name="amount" min="0.01" step="0.01" required/></label><label>Payment Method<select name="payment_method" defaultValue="CASH"><option value="CASH">Cash</option><option value="GCASH">GCash</option><option value="BANK_TRANSFER">Bank</option><option value="OTHER">Other</option></select></label><label className={styles.full}>Remarks<textarea name="remarks" rows={2}/></label><button>Save Capital Injection</button></form></section><section className={styles.card}><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Reference</th><th>Method</th><th>Recorded By</th><th>Remarks</th><th>Amount</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.injection_date).toLocaleString("en-PH")}</td><td>{r.reference_number}</td><td>{r.payment_method.replaceAll("_"," ")}</td><td>{r.created_by_name||"—"}</td><td>{r.remarks||"—"}</td><td><strong>{money(r.amount)}</strong></td></tr>)}</tbody></table></div></section></main>}
