import type { RowDataPacket } from "mysql2";
import { ArrowLeft, Bike, CircleDollarSign, ClipboardList, Printer, Wrench } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { pool } from "@/lib/db";
import { addJobOrderPart, addJobOrderPartByBarcode, addJobOrderService, removeJobOrderPart, removeJobOrderService, updateJobOrderDetails, updateJobOrderStatus } from "../actions";
import styles from "../job-orders.module.css";

interface JobRow extends RowDataPacket { id:number; job_order_number:string; client_name:string|null; mobile_number:string|null; motorcycle_id:number|null; plate_number:string|null; model_name:string|null; date_received:Date; estimated_finish:Date|null; status:string; priority:string; assigned_mechanic_id:number|null; mechanic_name:string|null; customer_concern:string|null; diagnosis:string|null; remarks:string|null; }
interface MechanicRow extends RowDataPacket { id:number; full_name:string; }
interface ServiceRow extends RowDataPacket { id:number; service_name:string; service_charge:number; }
interface ProductRow extends RowDataPacket { id:number; product_name:string; product_code:string; selling_price:number; quantity_on_hand:number; }
interface PartRow extends RowDataPacket { id:number; product_name:string; quantity:number; unit_price:number; line_total:number; }
interface JoServiceRow extends RowDataPacket { id:number; service_name:string; service_charge:number; mechanic_name:string|null; owner_share:number; mechanic_share:number; status:string; }
interface LogRow extends RowDataPacket { id:number; from_status:string|null; to_status:string; remarks:string|null; changed_by_name:string|null; changed_at:Date; }
interface LinkedSaleRow extends RowDataPacket { id:number; sale_number:string; status:string; }

export default async function JobOrderDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{success?:string;error?:string}>}) {
 const user=await getCurrentUser(); if(!user) redirect("/"); if(!["ADMIN","CASHIER","OWNER"].includes(user.role)) redirect("/dashboard");
 const {id}=await params; const jobId=Number(id); if(!Number.isFinite(jobId)) notFound(); const notice=await searchParams;
 const [jobs]=await pool.execute<JobRow[]>(`
 SELECT jo.*,c.client_name,c.mobile_number,m.plate_number,mm.model_name,mech.full_name mechanic_name
 FROM job_orders jo LEFT JOIN clients c ON c.id=jo.client_id LEFT JOIN motorcycles m ON m.id=jo.motorcycle_id LEFT JOIN motorcycle_models mm ON mm.id=m.model_id LEFT JOIN mechanics mech ON mech.id=jo.assigned_mechanic_id
 WHERE jo.id=? LIMIT 1`,[jobId]); const job=jobs[0]; if(!job) notFound();
 const [mechanics]=await pool.query<MechanicRow[]>(`SELECT id,full_name FROM mechanics WHERE is_active=1 ORDER BY full_name`);
 const [services]=await pool.query<ServiceRow[]>(`SELECT id,service_name,service_charge FROM services WHERE is_active=1 ORDER BY service_name`);
 const [products]=await pool.query<ProductRow[]>(`SELECT id,product_name,product_code,selling_price,quantity_on_hand FROM products WHERE is_active=1 AND quantity_on_hand>0 ORDER BY product_name`);
 const [parts]=await pool.execute<PartRow[]>(`SELECT id,product_name,quantity,unit_price,line_total FROM job_order_parts WHERE job_order_id=? ORDER BY id`,[jobId]);
 const [jobServices]=await pool.execute<JoServiceRow[]>(`SELECT js.id,js.service_name,js.service_charge,js.owner_share,js.mechanic_share,js.status,m.full_name mechanic_name FROM job_order_services js LEFT JOIN mechanics m ON m.id=js.mechanic_id WHERE js.job_order_id=? ORDER BY js.id`,[jobId]);
 const [logs]=await pool.execute<LogRow[]>(`SELECT id,from_status,to_status,remarks,changed_by_name,changed_at FROM job_order_status_logs WHERE job_order_id=? ORDER BY changed_at DESC,id DESC`,[jobId]);
 const [linkedSales]=await pool.execute<LinkedSaleRow[]>(`SELECT id,sale_number,status FROM sales WHERE job_order_id=? ORDER BY id DESC LIMIT 1`,[jobId]);
 const linkedSale=linkedSales[0]??null;
 const partsTotal=parts.reduce((s,r)=>s+Number(r.line_total),0); const serviceTotal=jobServices.filter(r=>r.status!=="CANCELLED").reduce((s,r)=>s+Number(r.service_charge),0); const total=partsTotal+serviceTotal;
 const canEdit=["ADMIN","CASHIER"].includes(user.role) && !["PAID","COMPLETED","RELEASED","CANCELLED"].includes(job.status);
 const statuses=["RECEIVED","INSPECTION","WAITING_PARTS","REPAIRING","READY_FOR_PAYMENT","PAID","COMPLETED","RELEASED","CANCELLED"];
 const localInput=(d:Date|null)=>d?new Date(new Date(d).getTime()-new Date(d).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
 return <main className={styles.page}>
  <Link href="/job-orders" className={styles.back}><ArrowLeft size={17}/> Back to Job Orders</Link>
  <section className={styles.hero}><div><div className={styles.eyebrow}>Workshop Job Order</div><h1>{job.job_order_number}</h1><p>{job.client_name??"Walk-in"} • {job.plate_number??"No plate"} {job.model_name?`• ${job.model_name}`:""}</p></div><div style={{display:"flex",alignItems:"center",gap:10,flexWrap:"wrap",justifyContent:"flex-end"}}><Link href={`/job-orders/${job.id}/print`} className={styles.secondary}><Printer size={16}/> Print Job Order</Link>{linkedSale?<Link href={`/pos/receipt/${linkedSale.id}`} className={styles.secondary}><Printer size={16}/> Reprint Receipt</Link>:null}<span className={styles.status}>{job.status.replaceAll("_"," ")}</span></div></section>
  {notice.success?<div className={styles.messages}><div className={styles.success}>{notice.success}</div></div>:null}{notice.error?<div className={styles.messages}><div className={styles.error}>{notice.error}</div></div>:null}
  <div className={styles.summaryGrid}>
   <div className={styles.summaryCard}><span>Parts</span><strong>₱{partsTotal.toFixed(2)}</strong></div>
   <div className={styles.summaryCard}><span>Services</span><strong>₱{serviceTotal.toFixed(2)}</strong></div>
   <div className={styles.summaryCard}><span>Job Total</span><strong>₱{total.toFixed(2)}</strong></div>
  </div>
  <div className={styles.grid} style={{marginTop:18}}>
   <div>
    <section className={styles.card}><h2><Bike size={20}/> Customer & Motorcycle</h2><div className={styles.line}><span>Customer</span><strong>{job.client_name??"—"}</strong></div><div className={styles.line}><span>Mobile</span><strong>{job.mobile_number??"—"}</strong></div><div className={styles.line}><span>Motorcycle</span><strong>{job.model_name??"—"}</strong></div><div className={styles.line}><span>Plate</span><strong>{job.plate_number??"—"}</strong></div><div className={styles.line}><span>Received</span><strong>{new Date(job.date_received).toLocaleString("en-PH")}</strong></div></section>
    <section className={styles.card}><h2>Concern / Diagnosis</h2><div className={styles.line}><span>Customer concern</span><strong>{job.customer_concern??"—"}</strong></div>{canEdit?<form action={updateJobOrderDetails}><input type="hidden" name="job_order_id" value={job.id}/><div className={styles.formGrid} style={{marginTop:14}}><label className={styles.field}><span>Assigned mechanic</span><select name="assigned_mechanic_id" defaultValue={job.assigned_mechanic_id??""}><option value="">Unassigned</option>{mechanics.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label className={styles.field}><span>Priority</span><select name="priority" defaultValue={job.priority}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>EMERGENCY</option></select></label><label className={styles.field}><span>Estimated finish</span><input type="datetime-local" name="estimated_finish" defaultValue={localInput(job.estimated_finish)}/></label><label className={`${styles.field} ${styles.full}`}><span>Diagnosis / inspection notes</span><textarea name="diagnosis" rows={4} defaultValue={job.diagnosis??""}/></label><label className={`${styles.field} ${styles.full}`}><span>Remarks</span><textarea name="remarks" rows={3} defaultValue={job.remarks??""}/></label></div><div className={styles.actions}><button className={styles.primary}>Save Details</button></div></form>:<><div className={styles.line}><span>Diagnosis</span><strong>{job.diagnosis??"—"}</strong></div><div className={styles.line}><span>Mechanic</span><strong>{job.mechanic_name??"Unassigned"}</strong></div></>}</section>
    <section className={styles.card}><h2>Parts</h2>{parts.map(p=><div className={styles.line} key={p.id}><div><strong>{p.product_name}</strong><div className={styles.muted}>{Number(p.quantity)} × ₱{Number(p.unit_price).toFixed(2)}</div></div><div className={styles.lineActions}><strong>₱{Number(p.line_total).toFixed(2)}</strong>{canEdit?<form action={removeJobOrderPart}><input type="hidden" name="job_order_id" value={job.id}/><input type="hidden" name="part_id" value={p.id}/><button className={styles.danger}>Remove</button></form>:null}</div></div>)}{parts.length===0?<div className={styles.muted}>No parts added yet.</div>:null}{canEdit?<><form action={addJobOrderPartByBarcode} className={styles.barcodeForm}><input type="hidden" name="job_order_id" value={job.id}/><label className={styles.field}><span>Scan Part Barcode</span><div className={styles.barcodeRow}><input name="barcode" autoFocus autoComplete="off" placeholder="Scan KL batch barcode or factory barcode" required/><button className={styles.primary} type="submit">Add Scanned Part</button></div><small>USB barcode scanner: scan the item and press Enter. Scanning the same item again increases its quantity.</small></label></form><div className={styles.orDivider}><span>or select manually</span></div><form action={addJobOrderPart} style={{marginTop:0}}><input type="hidden" name="job_order_id" value={job.id}/><div className={styles.formGrid}><label className={styles.field}><span>Product</span><select name="product_id" required defaultValue=""><option value="" disabled>Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_name} — ₱{Number(p.selling_price).toFixed(2)} ({Number(p.quantity_on_hand)} stock)</option>)}</select></label><label className={styles.field}><span>Quantity</span><input name="quantity" type="number" min="1" step="1" defaultValue="1" required/></label></div><div className={styles.actions}><button className={styles.primary}>Add Part</button></div><small className={styles.muted}>Adding a part does not deduct inventory yet. Stock is deducted only after payment.</small></form></>:null}</section>
    <section className={styles.card}><h2><Wrench size={20}/> Services</h2>{jobServices.map(s=><div className={styles.line} key={s.id}><div><strong>{s.service_name}</strong><div className={styles.muted}>{s.mechanic_name??"No mechanic"} • Mechanic share ₱{Number(s.mechanic_share).toFixed(2)}</div></div><div className={styles.lineActions}><strong>₱{Number(s.service_charge).toFixed(2)}</strong>{canEdit?<form action={removeJobOrderService}><input type="hidden" name="job_order_id" value={job.id}/><input type="hidden" name="job_order_service_id" value={s.id}/><button className={styles.danger}>Remove</button></form>:null}</div></div>)}{jobServices.length===0?<div className={styles.muted}>No services added yet.</div>:null}{canEdit?<form action={addJobOrderService} style={{marginTop:16}}><input type="hidden" name="job_order_id" value={job.id}/><div className={styles.formGrid}><label className={styles.field}><span>Service</span><select name="service_id" required defaultValue=""><option value="" disabled>Select service</option>{services.map(s=><option key={s.id} value={s.id}>{s.service_name} — ₱{Number(s.service_charge).toFixed(2)}</option>)}</select></label><label className={styles.field}><span>Mechanic</span><select name="mechanic_id" defaultValue={job.assigned_mechanic_id??""}><option value="">Use assigned mechanic</option>{mechanics.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label></div><div className={styles.actions}><button className={styles.primary}>Add Service</button></div></form>:null}</section>
   </div>
   <div>
    <section className={styles.card}><h2><CircleDollarSign size={20}/> Status</h2><div className={styles.line}><span>Current</span><strong>{job.status.replaceAll("_"," ")}</strong></div><div className={styles.line}><span>Priority</span><strong>{job.priority}</strong></div><div className={styles.line}><span>Mechanic</span><strong>{job.mechanic_name??"Unassigned"}</strong></div>{["ADMIN","CASHIER"].includes(user.role)?<form action={updateJobOrderStatus} style={{marginTop:16}}><input type="hidden" name="job_order_id" value={job.id}/><label className={styles.field}><span>Change status</span><select name="status" defaultValue={job.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className={styles.field} style={{marginTop:12}}><span>Status note</span><input name="status_remarks" placeholder="Optional note"/></label><div className={styles.actions}><button className={styles.primary}>Update Status</button></div></form>:null}</section>
    {job.status==="READY_FOR_PAYMENT"?<section className={styles.card}><h2>Ready for Payment</h2><p className={styles.muted}>The job is ready for payment. Open POS to load its customer, motorcycle, parts, services, and mechanic. Inventory will be deducted only when payment succeeds.</p><Link href={`/pos?job_order_id=${job.id}`} className={styles.primary}>Open POS</Link></section>:null}
    {linkedSale?<section className={styles.card}><h2>Paid Sale / Receipt</h2><div className={styles.line}><span>Receipt</span><strong>{linkedSale.sale_number}</strong></div><div className={styles.line}><span>Sale Status</span><strong>{linkedSale.status}</strong></div><Link href={`/pos/receipt/${linkedSale.id}`} className={styles.primary}><Printer size={16}/> Reprint Receipt</Link></section>:null}
    <section className={styles.card}><h2><ClipboardList size={20}/> Status Timeline</h2><div className={styles.timeline}>{logs.length===0?<div className={styles.muted}>No status history yet.</div>:logs.map(l=><div key={l.id} className={styles.timelineItem}><strong>{l.to_status.replaceAll("_"," ")}</strong><small>{new Date(l.changed_at).toLocaleString("en-PH")} • {l.changed_by_name??"System"}</small>{l.remarks?<div>{l.remarks}</div>:null}</div>)}</div></section>
   </div>
  </div>
 </main>;
}
